language: cpp

env:
  - tbs_arch=x86
  - tbs_arch=x64

os:
  - linux
#  - osx

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install nasm
  - if [ "$tbs_arch" = "x86" ];
    then
      sudo apt-get -y install gcc-multilib;
    fi

script:
  - ./thumbs.sh make
  - ./thumbs.sh check
